---
- name: Create defined groups
  loop: "{{ groups_general + groups_extra }}"
  loop_control:
    label: "{{ item.name }}"
  ansible.builtin.group:
    name: "{{ item.name }}"
    gid: "{{ omit if item.gid is undefined else item.gid }}"
    non_unique: "{{ omit if item.non_unique is undefined else item.non_unique }}"
    system: "{{ false if item.system is undefined else item.system }}"
    state: "{{ 'present' if item.state is undefined else item.state }}"
  tags:
    - groups

...
